monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # Add special handler for CSRF debugging
        csrf_debug:
            type: stream
            path: '%kernel.logs_dir%/csrf_debug.log'
            level: debug
            channels: ['app']

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: ['!event']
            # Add special handler for CSRF debugging
            console:
                type: console
                process_psr_3_messages: false
                channels: ['!event', '!doctrine', '!console']
